name: deploy-aosus-wordpress

on:
  push:
    paths:
      - '.github/workflows/aosus-wordpress.yml'
      - 'aosus-wordpress/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: aosus.org
      url: https://aosus.org
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_SECRET }}
          tags: tag:deploy-ci
          hostname: Github-actions
          version: ${{ vars.TAILSCALE_VERSION }}
          cache: true

      - name: Add secrets to compose
        env:
          MARIADB_PASSWORD: ${{ secrets.aosus_wordpress_mariadb_password }}
          MARIADB_ROOT_PASSWORD: ${{ secrets.aosus_wordpress_mariadb_root_password }}
        run: |
          sed -i "s|(aosus_wordpress_mariadb_password)|$MARIADB_PASSWORD|g" $GITHUB_WORKSPACE/aosus-wordpress/docker-compose.yml
          sed -i "s|(aosus_wordpress_mariadb_root_password)|$MARIADB_ROOT_PASSWORD|g" $GITHUB_WORKSPACE/aosus-wordpress/docker-compose.yml

      - name: Start Deployment
        uses: FarisZR/docker-compose-gitops-action@v1.0.1
        env:
          MARIADB_PASSWORD: ${{ secrets.aosus_wordpress_mariadb_password }}
          MARIADB_ROOT_PASSWORD: ${{ secrets.aosus_wordpress_mariadb_root_password }}
        with:
          remote_docker_host: ${{ secrets.server_address }}
          tailscale_ssh: true # no need for manual private and public keys
          compose_file_path: aosus-wordpress/docker-compose.yml
          args: -p aosus-wordpress up -d --remove-orphans
          upload_directory: true
          docker_compose_directory: aosus-wordpress